// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package store

import (
	"database/sql"
	"time"
)

type File struct {
	ID         int64        `db:"id" json:"id"`
	Name       string       `db:"name" json:"name"`
	ObjectName string       `db:"object_name" json:"object_name"`
	Owner      int64        `db:"owner" json:"owner"`
	CreatedAt  time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt  sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at"`
}
