// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package relation

import (
	"database/sql"
	"time"
)

type UserFileRelation struct {
	UserID    int64        `db:"user_id" json:"user_id"`
	FileID    int64        `db:"file_id" json:"file_id"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
}
